<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists

import numpy as np
def matrix_mul(A, B):
    # write your code
    #get number of rows and column of matrix A using shape function
    Ai, Aj = np.shape(A)
    #get number of rows and column of matrix B using shape function
    Bi, Bj = np.shape(B)
    #create zero matrix of shape number of rowsin matrix-A and number of column of matrix_B
    C=np.zeros(shape=(Ai, Bj))
    #check the condition where rows of matrix_A and columns of matix_B are equal
    if Aj == Bi:
      #iterate through rows of matrix_A
      for i in range(Ai):
        #iterate through columns of matrix_B
        for j in range(Bj):
          #iterate through rows of matrix_B
          for k in range(Bi):
            C[i][j] += A[i][k] * B[k][j]
      return(C)
    else:
      print("Matrix Multiplication not possible")

A = [[1, 3, 4], [2, 5, 7], [5, 9, 6]]
B = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

#A = [[1, 2], [3, 4]]
#B = [[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]

#A = [[1, 2], [3, 4]]
#B = [[1, 4], [5, 6], [7, 8], [9, 6]]
matrix_mul(A, B)

array([[1., 3., 4.],
       [2., 5., 7.],
       [5., 9., 6.]])

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [2]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude

    #initialize sum=0 and calculate sum of elements in list
    sum = 0
    for i in A:
      sum += i
      #normalize the elements in list and add in new list(cum_lst)
    x=0
    cum_lst=[]
    for i in A:
      cum_lst.append(x+i / sum)
      x = x+i / sum
      #cum_lst has cumulative normalised sum values of list-A

      #get random values between 0 and 1
      r=uniform(0, 1)
    #iterate through cum_lst to check random value is in which bin of cum_lst elements
    for i in range(len(cum_lst)):
      #number which has larger magnitude has larger bin range in cum_lst
      if r < cum_lst[i]:
        return A[i]


def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
sampling_based_on_magnitued()

100
100
79
79
100
79
100
79
100
45
45
100
79
45
6
79
28
79
45
79
28
10
100
79
13
79
13
100
10
45
28
100
28
100
27
79
45
45
28
79
100
100
100
45
100
79
100
100
100
28
79
79
100
100
100
100
100
45
100
79
45
45
100
100
45
45
27
5
100
79
79
100
100
28
10
100
27
79
10
45
100
100
45
79
100
100
79
100
45
100
28
28
79
79
100
5
100
28
79


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [3]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    # 
    #Replacing all non digit characters into empty character(\D = other than digit)
    replace1 = re.sub(r'\D', '', String)

    #Replacing all digits into #(\d = digit)
    replace2 = re.sub(r'\d', '#', replace1)
    return(replace2) # modified string which is after replacing the # with digits

String = '234'
replace_digits(String)

'###'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [4]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
import math

def percentile(data, percentile):
    size = len(data)
    return sorted(data)[int((size * percentile) / 100) - 1]
    #return sorted(data)[int(math.ceil((size * percentile) / 100)) - 1]

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    # write code for computing top top 5 students

    marks, students = zip(*sorted(zip(marks,students)))                  #arranging both marks and students in ascending order
    top_5_students = [(students[-i], marks[-i]) for i in range(1, 6)]    #Taking top 5 students based on marks by reverse indexing

    # write code for computing top least 5 students
    least_5_students = [(students[i], marks[i]) for i in range(5)]       #Taking least 5 students based on marks

    # write code for computing top least 5 students
    p_25 = percentile(marks, 25)                                         #Calculate 25th percentile using percntile method
    p_75 = percentile(marks, 75)                                         #Calculate 75th percentile using percntile method
    students_within_25_and_75 = [(students[i], marks[i]) for i in range(len(marks)) if marks[i] > p_25 and marks[i] < 75]   #selecting students within 25th and 75th percentile
    
    return top_5_students, least_5_students, students_within_25_and_75

Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(Students, Marks)

print(top_5_students)
print(least_5_students)
print(students_within_25_and_75)

[('student8', 98), ('student10', 80), ('student2', 78), ('student5', 48), ('student7', 47)]
[('student3', 12), ('student4', 14), ('student9', 35), ('student6', 43), ('student1', 45)]
[('student9', 35), ('student6', 43), ('student1', 45), ('student7', 47), ('student5', 48)]


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [5]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    cd_lst = []                          #creating empty list to store closest points
    p, q = P                             #assign tuple values by tuple unpacking
    for a,b in S:                        #iterate through list of tuples
      x, y = a, b                        #assign tuple values by tuple unpacking
      cos_dis = math.acos(((x*p)+(y*q)) / ((math.sqrt((x**2) + (y**2))) * (math.sqrt((p**2) + (q**2)))))     #calculate cosine_distance
      cd_lst.append(cos_dis)             #adding cosine_distance to list
    cd_lst, S = zip(*sorted(zip(cd_lst, S)))          #sorting both list in ascending order
    closest_points_to_p = [S[i] for i in range(5)]    #iterate through sorted list to take closest points
    return closest_points_to_p

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(points) #print the returned values

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [6]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

def coeff(line):
  l=['']
  #iterating through each character in line equation
  for i in line:
    #checking each character is '.','-' or digit
    if i in ['.','-'] or i.isdigit():
      #if its true add to list
      l[len(l)-1] += i
    else:
      if len(l[len(l)-1]) != 0:
        l.append('')
  #getting coefficient of equation as a,b,c
  a = float(l[0])
  b = float(l[1])
  c = float(l[2])
  #returning a,b,c
  return a, b, c

# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):

    #redck = red(red, line)
    #initialize red count to zero
    rdcount = 0
    #getting coefficient of line equation
    a, b, c = coeff(line)
    #iterate through each points in red list
    for i in red:
      #get x1, x2 by tuple unpacking
      x1, x2 = i[0], i[1]
      #finding direction of red point by applying formula
      r = (a*x1)+(b*x2)+c
      #checking direction of point
      if r>0:
        #increase red count by one if r>0
        rdcount += 1
    #if red count equals length of red points declare red vairable as YES otherwise NO
    if rdcount == len(red):
      red = 'yes'
    else:
      red = 'No'

    #blueck = blue(blue, line)
    #initialize blue count to zero
    blcount = 0
    #getting coefficient of line equation
    a, b, c = coeff(line)
    #iterate through each points in blue list
    for i in blue:
      #get x1, x2 by tuple unpacking
      x1, x2 = i[0], i[1]
      #finding direction of blue point by applying formula
      bl = (a*x1)+(b*x2)+c
      #checking direction of point
      if bl<0:
        blcount += 1
    #if blue count equals length of blue points declare red vairable as YES otherwise NO
    if blcount == len(blue):
      blue = 'yes'
    else:
      blue = 'No'
    
    #both red and blue are YES then declare final result as YES otherwise NO
    if red == 'yes' and blue == 'yes':
      yes_or_no = 'YES'
    else:
      yes_or_no = 'NO'

    return yes_or_no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [7]:
def curve_smoothing(string):
  #split the string using .split() by comma
  string = string.split(',')
  #initialize below variables to zero, false
  fcount = 0
  prect =0
  fill = 0
  digit_present = False
  #iterate through spiltted string
  for i in string:
    further = False
    #add fcount by one
    fcount += 1
    #check each element instring is digit
    if i.isdigit():
      #assign fcount value to ct
      ct = fcount
      
      #check digit present in 1st position
      if fcount ==1:
        #check for any other digit present in between(start to end) of spiltted string...if present assign digit_present=true
        for j in range(fcount, len(string)):
          if string[j].isdigit():
            digit_present = True

        #if igit not present in between of total string divide the 1st value by lenght of string and fill the string
        if not digit_present:
          a = int(i)
          fill = a/(len(string))
          fill = round(fill, 2)
          for i in range(ct-1, len(string)):
            string[i] = fill
          break
      
      #if any digit present in between fill missing values taking sum of two numbers(from 1st to digit position) and divide it by its range
      rng = ct - prect
      a = int(i)
      fill += a
      fill = fill/rng
      fill = round(fill, 2)
      for k in range(prect, ct):
        string[k] = fill
      prect = ct-1

      #checking any other number present further
      for h in range(ct+1, len(string)):
          if string[h].isdigit():
            further = True
      
      #if there is no number present afterwards fill remaining missing values
      if not further:
        fill = fill/(len(string) - (ct-1))
        for d in range(ct-1, len(string)):
          string[d] = fill
        break

  return string

S=  "_,_,_,24"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[6.0, 6.0, 6.0, 6.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [8]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

def prob_s(A, s):                   #fingding count if second statement in conditional probability is present in A
  count = 0                         #initilising count with zero
  for i in A:                       #iterate through elemnts of A
    if i[1] == s:                   # if s present in A increase count by one
      count += 1
  return (count)

def inter_prob(A, f, s):             #finding count if both inputs are present in A
  count = 0                          #initialising count to zero
  for i in A:                        #iterate through elements in A
    if i[0] == f and i[1] == s:      #if both inputs are present increase count by one
      count += 1
  return count

# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    # print the output as per the instructions
  print("P(F=F1|S==S1)=", inter_prob(A, 'F1', 'S1'), "/", prob_s(A, 'S1'), "\tP(F=F1|S==S2)=", inter_prob(A, 'F1', 'S2'), "/" ,prob_s(A, 'S2'), "\tP(F=F1|S==S3)=", inter_prob(A, 'F1', 'S3'), "/", prob_s(A, 'S3'))
  print("P(F=F2|S==S1)=", inter_prob(A, 'F2', 'S1'), "/", prob_s(A, 'S1'), "\tP(F=F2|S==S2)=", inter_prob(A, 'F2', 'S2'), "/" ,prob_s(A, 'S2'), "\tP(F=F2|S==S3)=", inter_prob(A, 'F2', 'S3'), "/", prob_s(A, 'S3'))
  print("P(F=F3|S==S1)=", inter_prob(A, 'F3', 'S1'), "/", prob_s(A, 'S1'), "\tP(F=F3|S==S2)=", inter_prob(A, 'F3', 'S2'), "/" ,prob_s(A, 'S2'), "\tP(F=F3|S==S3)=", inter_prob(A, 'F3', 'S3'), "/", prob_s(A, 'S3'))
  print("P(F=F4|S==S1)=", inter_prob(A, 'F4', 'S1'), "/", prob_s(A, 'S1'), "\tP(F=F4|S==S2)=", inter_prob(A, 'F4', 'S2'), "/" ,prob_s(A, 'S2'), "\tP(F=F4|S==S3)=", inter_prob(A, 'F4', 'S3'), "/", prob_s(A, 'S3'))
  print("P(F=F5|S==S1)=", inter_prob(A, 'F5', 'S1'), "/", prob_s(A, 'S1'), "\tP(F=F5|S==S2)=", inter_prob(A, 'F5', 'S2'), "/" ,prob_s(A, 'S2'), "\tP(F=F5|S==S3)=", inter_prob(A, 'F5', 'S3'), "/", prob_s(A, 'S3'))
  

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F=F1|S==S1)= 1 / 4 	P(F=F1|S==S2)= 1 / 3 	P(F=F1|S==S3)= 0 / 3
P(F=F2|S==S1)= 1 / 4 	P(F=F2|S==S2)= 1 / 3 	P(F=F2|S==S3)= 1 / 3
P(F=F3|S==S1)= 0 / 4 	P(F=F3|S==S2)= 1 / 3 	P(F=F3|S==S3)= 1 / 3
P(F=F4|S==S1)= 1 / 4 	P(F=F4|S==S2)= 0 / 3 	P(F=F4|S==S3)= 1 / 3
P(F=F5|S==S1)= 1 / 4 	P(F=F5|S==S2)= 0 / 3 	P(F=F5|S==S3)= 0 / 3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [9]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
  S1 = S1.split(" ")                 #splitting S1 and S2 by comma
  S2 = S2.split(" ")
  count = 0                           # initialie count with zero
  for i in S1:                        #iterating through elements in S1
    if i in S2:                       #finding elements in S1 present in S2
      count += 1                      #incrementing count
  a=count

  b=[i for i in S1 if i not in S2]     #List comprehensive with for loop with if condition to filter out elements in S1 but not in S2

  c=[i for i in S2 if i not in S1]     #List comprehensive with for loop with if condition to filter out elements in S2 but not in S1

  return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a, b, c)

7 ['first', 'F', '5'] ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [10]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure

def log(x, b):
  res = (99999999*(x**(1/99999999)-1)) / (99999999*(b**(1/99999999)-1))
  return res


def compute_log_loss(A):
  s=0
  for i in A:                                                      #iterating through elements in A
    s += (((i[0]*log(i[1], 10)) + ((1-i[0])*log(1-i[1], 10))))     #Applying formula
  loss = (-s/len(A))
  return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.4243099249901754
