In [1]:
import numpy as np
import pandas as pd
import plotly
import plotly.figure_factory as ff
import plotly.graph_objs as go
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
data = pd.read_csv('/content/drive/My Drive/Dataset/8_LinearModels/task_b.csv')
data = data.iloc[:,1:]

In [4]:
#correlation with y
data.corr()['y']

f1    0.067172
f2   -0.017944
f3    0.839060
y     1.000000
Name: y, dtype: float64

In [5]:
#calculating standars deviation, mean, variance
print(data.std(), data.mean(), data.var())

f1      488.195035
f2    10403.417325
f3        2.926662
y         0.501255
dtype: float64 f1      10.180031
f2    1299.986739
f3       5.001840
y        0.500000
dtype: float64 f1    2.383344e+05
f2    1.082311e+08
f3    8.565349e+00
y     2.512563e-01
dtype: float64


In [6]:
#assigning x and y
x = data[['f1', 'f2', 'f3']].values
y = data['y'].values

In [7]:
x.shape, y.shape

((200, 3), (200,))

In [8]:
# #spliting train and test data
# x_tr = x[:160]
# x_te = x[160:]

# y_tr = y[:160]
# y_te = y[160:]

Feature importance using logloss

In [9]:
from sklearn.linear_model import SGDClassifier
clf_l = SGDClassifier(loss = 'log')
clf_l.fit(x, y)
clf_l.coef_[0]

array([ 5927.07320196,  8831.10951099, 10377.12662112])

Feature importance using hinge loss

In [10]:
from sklearn.linear_model import SGDClassifier
clf_svm = SGDClassifier(loss = 'hinge')
clf_svm.fit(x, y)
clf_svm.coef_[0]

array([ 22861.11470802, -18247.22992924,  10283.76719508])

Feature importance using logloss with column standarization

In [11]:
scalar = StandardScaler()
xf = scalar.fit_transform(x)
clf_l = SGDClassifier(loss = 'log')
clf_l.fit(xf, y)
clf_l.coef_[0]

array([ 0.51977047, -1.0706472 ,  9.66278315])

Feature importance using hinge loss with column standarization

In [12]:
clf_svm = SGDClassifier(loss = 'hinge')
clf_svm.fit(xf,y)
clf_svm.coef_[0]

array([-5.95672274e-03,  2.19745672e+00,  2.28698182e+01])